<a href="https://colab.research.google.com/github/Sakib3602/ML-Work/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy ND-Array**

In [ ]:
import numpy as np
arr1 = np.array([10,20,30,40])
print(arr1)
print(arr1.ndim)

arr2 = np.array([[10,20],[40,50]])
print(arr2)
print(arr2.ndim)

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,22,33]]])

print(arr3)
print(arr3.ndim)

[10 20 30 40]
1
[[10 20]
 [40 50]]
2
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 22 33]]]
3


# **Shape**

In [ ]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(4,)
(2, 2)
(2, 2, 3)


# **Size**

In [ ]:
print(arr1.size)
print(arr2.size)
print(arr3.size)

4
4
12


type

In [ ]:
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

int64
int64
int64


In [ ]:
s = np.array([10,20.8,"s"])
print(s)
print(s.dtype)

['10' '20.8' 's']
<U32


In [ ]:
a = np.array([10,20.8,"k"])
print(a )

['10' '20.8' 'k']


# *Selecting data type***

In [ ]:
m = np.array([10,20,30] , dtype = np.int8)
print(m)


[10 20 30]


# **Convert to Nd array**

In [ ]:
a = [10,3,2,1,]
aa = np.array(a)
print(aa, "===" , type(aa))


[10  3  2  1] === <class 'numpy.ndarray'>


# Tupple

In [ ]:
a = (2,3,4)
a = np.array(a)
print(a , "== ", type(a))

[2 3 4] ==  <class 'numpy.ndarray'>


# **Set convert must convert in list first otherwise type will be object**

In [ ]:
x ={1,2,4}
x = np.array(list(x))
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int64


# ***Dictionary must convert in list first otherwise type will be object***

In [ ]:
d = { 'a' : 10, "b" : 20, "c":30}
print(d)

d1 = d.keys()
d2 = d.values()
d3 = d.items()
print(d1)
print(d2)
print(d3)




print("===================")
dic = np.array(list(d1))
print(dic)
print(dic.dtype)
dic1 = np.array(list(d2), dtype= np.int8)
print(dic1)
print(dic1.dtype)
print(type(dic1))

{'a': 10, 'b': 20, 'c': 30}
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
['a' 'b' 'c']
<U1
[10 20 30]
int8
<class 'numpy.ndarray'>


# **Zeros**

In [ ]:
op = np.zeros((2,3))
print(op)

ak = np.zeros_like(arr3)
print(ak)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


Ones


In [ ]:
one = np.ones((2,2))
ons = np.ones_like(arr3)

print(one)
print(ons)

[[1. 1.]
 [1. 1.]]
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


**Array creation with random **

In [ ]:
s = np.random.rand(2,3)
print(s)

ss = np.random.randint(1,9 , (1,7))
print(ss)
ss = np.random.uniform(1,9 , (3,3,3))
print(ss)

[[0.86088494 0.35207581 0.35516174]
 [0.22346495 0.43173288 0.7306844 ]]
[[3 2 5 8 7 8 6]]
[[[2.10665691 4.50361721 2.11953068]
  [1.21555615 4.9752339  4.00929565]
  [3.68268831 8.70111971 8.60579524]]

 [[8.60994334 2.14496841 2.19389881]
  [3.93576886 8.33351906 8.81913124]
  [3.34712027 6.90547666 6.43973383]]

 [[2.34715523 8.16383582 6.29131613]
  [3.54434117 3.24901418 8.02180166]
  [3.9707905  6.4676066  4.82248944]]]


with rang => (first , end , step)

In [ ]:
k = np.arange(1,10, 1)
print(k)
k = k.reshape(3,3)
print(k)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **Diagonal matrix**

In [ ]:
v = np.diag([1,2,3])
print(v)
print(v.shape)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
(3, 3)


# **Identity matrix**

In [ ]:
i = np.eye(3)
print(i)
print(i.shape)
print("---------")
i = np.eye(3,4,1) # k = - +
print(i)
print(i.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
---------
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(3, 4)


# **Indexing ND array**

In [ ]:
print(arr1)
print(arr2)

# arr1[1] = 200
# print(arr1)

arr2[0][1] = 0
print(arr2)

[ 10 200  30  40]
[[ 10  20]
 [ 30 300]]
[[ 10   0]
 [ 30 300]]


# **Slicing**

In [ ]:
ar1 = arr1[0:3:2]
print(ar1)

aq = arr2[0:1,0:1]
print(aq)

aq = arr2[0:1,]
print(aq)

[10 30]
[[10]]
[[10  0]]


# **Iterate**

In [ ]:
m = np.array([[1,2,3,4],[5,6,7,8]])
print(m)

for i in m:
  for j in i:
    print(j)

print("np.nditer()")

for i in np.nditer(m):
  print(i)

[[1 2 3 4]
 [5 6 7 8]]
1
2
3
4
5
6
7
8
np.nditer()
1
2
3
4
5
6
7
8


In [ ]:
ax = np.array([1,2,3,4,5])
ax[1:4] = 0
print(ax)

[1 0 0 0 5]
