<a href="https://colab.research.google.com/github/Sakib3602/ML-Work/blob/main/Numpy_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reshape**

In [11]:
import numpy as np
arr = np.random.randint(1,100, size = (10,5))
print(arr)
print(arr.shape)

b= arr.reshape(5,10)
print(b.shape)


[[58  5 95 94 53]
 [15 38 15 90 68]
 [37 39 67 27 68]
 [51 64 84 71 72]
 [53 48  5 28 97]
 [21 22 13 77 85]
 [91 63 70 56 76]
 [76 91 56 55 44]
 [52 79 57 70 20]
 [83  5 51 65 79]]
(10, 5)
(5, 10)


#**Flatten**
flatten use for convert into 1 dimention from any Dimention

In [14]:
# row wise
ax = b.flatten()
print(ax)

# colum wise => F means colum wise and C means Row wise
ax = np.ravel(b , order ='F')
print(ax)

[58  5 95 94 53 15 38 15 90 68 37 39 67 27 68 51 64 84 71 72 53 48  5 28
 97 21 22 13 77 85 91 63 70 56 76 76 91 56 55 44 52 79 57 70 20 83  5 51
 65 79]
[58 37 53 91 52  5 39 48 63 79 95 67  5 70 57 94 27 28 56 70 53 68 97 76
 20 15 51 21 76 83 38 64 22 91  5 15 84 13 56 51 90 71 77 55 65 68 72 85
 44 79]


# ***Concatenation***
Note : Row colum must check
Row  wise korar somoy colum same thakte hobe
colum wise korar somoy colum same thakte hobe

In [20]:
s = np.random.randint(1,20 , size = (2,3))
s1 = np.random.randint(20,30 , size = (2,3))

print(s)
print(s1)

dd = np.concatenate((s,s1) , axis= 1)
ddd = np.concatenate((s,s1) , axis= 0)
print("colum",dd)
print("row",ddd)

[[ 5 17 14]
 [11  4 13]]
[[28 23 24]
 [25 22 23]]
colum [[ 5 17 14 28 23 24]
 [11  4 13 25 22 23]]
row [[ 5 17 14]
 [11  4 13]
 [28 23 24]
 [25 22 23]]


**Transpose**
row gula k colum

In [31]:
h = np.array([[10,20,30],[40,50,60]])
print(h)

transpose = h.T
print(transpose)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


**Array Split**

In [34]:
xp = np.random.randint(1,10, size = (10,))
print(xp)
o = np.array_split(xp, 3)
print(o)

# np.split only for equal distribution
xp = np.random.randint(1,10, size = (12,))
print(xp)
o = np.split(xp, 3)
print(o)


[6 6 6 1 2 7 2 6 6 4]
[array([6, 6, 6, 1]), array([2, 7, 2]), array([6, 6, 4])]
[8 1 7 5 5 3 5 3 5 8 7 7]
[array([8, 1, 7, 5]), array([5, 3, 5, 3]), array([5, 8, 7, 7])]


# **Arithmetic**

In [37]:
n = np.array([10,20,30,40])
n1 = np.array([1,2,3,4])
# + - * / % anything     must row colum same
add = n + n1  # can use np.add(n,n1)
print(add)

[11 22 33 44]


# ***https://www.geeksforgeeks.org/python/numpy-mathematical-function/***

sin,log,cos,log10,any thing

**Brodcusting**
1 ta number diye all arithmetic operation can be done


can use in matrix and vector

In [39]:
x = np.array([10,20,30])

v = x ** 2
c = x + 2

print(v)
print(c)

[100 400 900]
[12 22 32]
