<a href="https://colab.research.google.com/github/Sakib3602/ML-Work/blob/main/Numpy_Qus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [46]:
import numpy as np
a = np.random.randint(1,20, (5,5))
print(a)

[[ 4  1 19 12  4]
 [13 11  4  4  6]
 [ 1 11 12 14  5]
 [ 4 18  4  3  2]
 [13 17  5  7 13]]


In [47]:
a[:,2] = 1
print(a)

[[ 4  1  1 12  4]
 [13 11  1  4  6]
 [ 1 11  1 14  5]
 [ 4 18  1  3  2]
 [13 17  1  7 13]]


In [48]:
a = np.random.randint(1,16, (4,4))
np.fill_diagonal(a,0)
print(a)

[[ 0 10 12  2]
 [14  0  3  4]
 [11 12  0  6]
 [ 5  4  6  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [49]:
a = np.random.randint(1,36, (6,6))
print(a)
b = a[3:6,2:5]
print(b)

[[ 7 27 15 28  5 22]
 [33 13 13 20 25 35]
 [12 24 32  8 27 23]
 [ 8  9 29 18  1 11]
 [ 3 33 14 23 16  9]
 [25 15  1 17 10 34]]
[[29 18  1]
 [14 23 16]
 [ 1 17 10]]


In [50]:
a = np.random.randint(1,25, (5,5))
print(a)

b = np.concatenate((a[0],a[-1],a[:,0],a[:,-1]))

print(b)

[[23  5 17 20 22]
 [10 19  2  1 16]
 [ 8 13 24 24 19]
 [ 7 15 24  5 10]
 [23 12 17 11  5]]
[23  5 17 20 22 23 12 17 11  5 23 10  8  7 23 22 16 19 10  5]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [51]:
x = np.array([10,20,30])
y = np.array([1,2,3])

sum = x + y
mul = x * y
div = x / y
print(sum)
print(mul)
print(div)

[11 22 33]
[10 40 90]
[10. 10. 10.]


In [52]:
c = np.random.randint(1,16, (4,4))
print(c)
#row
row = 0
col = 0
for i in range(4):
  first = c[i,].sum()
  row += first
for i in range(4):
  first = c[i,].sum()
  col += first

print(row)
print(col)

[[ 1 12  4  8]
 [14  8 10  7]
 [ 1 10  7  8]
 [ 9 11  6 12]]
128
128


### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [53]:
sta = np.random.randint(1,25,(5,5))
print(sta)

m = np.mean(sta)
stand = np.std(sta)
print(round(m))
print(stand)

[[20 21 10  9 16]
 [ 5 20  4  8  4]
 [ 8  6 20 21  4]
 [15 20 10  1 21]
 [17 23  9  8 11]]
12
6.747325396036566


### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [54]:
mat = np.array([[10,20,30],[1,2,3]])

va = np.array([1,2,3])
result = mat + va
print(result)

[[11 22 33]
 [ 2  4  6]]


In [55]:
mat = np.array([[10,20,30,40],[11,12,3,40]])

va = np.array([1,2,3,4])
result = mat - va
print(result)

[[ 9 18 27 36]
 [10 10  0 36]]


In [56]:
#exploring
mat = np.array([[10,20,30,40],[11,12,3,40]])
print(mat)

p = np.sort(mat,axis=0)

print(p)

[[10 20 30 40]
 [11 12  3 40]]
[[10 12  3 40]
 [11 20 30 40]]


In [57]:
# exploring search
d = np.array([1,2,3,4,5,6,9])
p = np.where(d==4)
p = np.where(d > 4 , d, 0)
print(p)

[0 0 0 0 5 6 9]


### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [58]:
a = np.random.randint(2,3,(2,3))
b = np.random.randint(2,3,(3,2))
x = np.dot(a,b)
print(x)

[[12 12]
 [12 12]]


### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [59]:
a = np.random.randint(1,9, (3,3))
print(a)
a.reshape(1,9)
print(a)
a.reshape(9,1)
print("-----------")
print(a)

[[5 8 1]
 [6 3 8]
 [5 6 5]]
[[5 8 1]
 [6 3 8]
 [5 6 5]]
-----------
[[5 8 1]
 [6 3 8]
 [5 6 5]]


### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [60]:
a = np.random.randint(1,20, (4,4))
print(a[a>=10])

[10 11 19 15 13 14 16 14 18 11]
