<a href="https://colab.research.google.com/github/Sakib3602/ML-Work/blob/main/Numpy_Qus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
import numpy as np
a = np.random.randint(1,20, (5,5))
print(a)

[[11 10  8 14  1]
 [ 7  5  2 14  9]
 [18 15  2 11 16]
 [ 6 14  3 19 15]
 [ 4  9  2 19 10]]


In [2]:
a[:,2] = 1
print(a)

[[11 10  1 14  1]
 [ 7  5  1 14  9]
 [18 15  1 11 16]
 [ 6 14  1 19 15]
 [ 4  9  1 19 10]]


In [5]:
a = np.random.randint(1,16, (4,4))
np.fill_diagonal(a,0)
print(a)

[[ 0  9  1  2]
 [12  0  7  5]
 [ 4  3  0  8]
 [10  9  4  0]]


### Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
a = np.random.randint(1,36, (6,6))
print(a)
b = a[3:6,2:5]
print(b)

[[26  6 32  1  9 10]
 [13 34 23 12 21 32]
 [19  1 28 24 11 28]
 [ 3 15 34 19 12 18]
 [ 4  1  7 22 18  3]
 [ 8  4 25 23 17 10]]
[[34 19 12]
 [ 7 22 18]
 [25 23 17]]


In [19]:
a = np.random.randint(1,25, (5,5))
print(a)

b = np.concatenate((a[0],a[-1],a[:,0],a[:,-1]))

print(b)

[[ 9  3 10 20 15]
 [ 7 16 15 21 12]
 [16  4 13  7  7]
 [ 8 18 20 13  9]
 [ 5  4 11  9 16]]
[ 9  3 10 20 15  5  4 11  9 16  9  7 16  8  5 15 12  7  9 16]


### Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

### Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Linear Algebra

1. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### **Boolean Indexing**

1. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.